### ISSUE TITLE
badge to link to discord

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang.com#24]
## Context/Problem

1. Nobody sees CTAs in product description "join discord"
2. The CTA in a product description makes the description unnecessarily longer

![CleanShot 2024-04-03 at 11.17.11@2x.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/216d1d9c-7556-454a-a276-f249ede9cf74/802ac41e-12e4-4422-940a-a4dfa8caee6c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8yMTZkMWQ5Yy03NTU2LTQ1NGEtYTI3Ni1mMjQ5ZWRlOWNmNzQvODAyYWM0MWUtMTJlNC00NDIyLTk0MGEtYTRkZmE4Y2FlZTZjIiwiaWF0IjoxNzEyMTU3NDQxLCJleHAiOjMzMjgyNzE3NDQxfQ.c8OMTM30TXNoWmNheeOnmfRfeKkUcStBWCTvF1lHoEo "=894x")

## Proposal

Add a discord badge on product pages that joins our discord and links to the correct channel.

(Maybe add a badge to the github issues too?)

![CleanShot 2024-04-03 at 11.17.23@2x.png](https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/a3703ef0-535b-446d-bc84-328847efb6e0/83a3e6e3-f35d-4817-8ffd-c484f6926dc4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9hMzcwM2VmMC01MzViLTQ0NmQtYmM4NC0zMjg4NDdlZmI2ZTAvODNhM2U2ZTMtZjM1ZC00ODE3LThmZmQtYzQ4NGY2OTI2ZGM0IiwiaWF0IjoxNzEyMTU3NDc5LCJleHAiOjMzMjgyNzE3NDc5fQ.VbPMBaWddj_DRUcUgEmKw6_pvxXGDU9vjAQm_lwzUNI "=1840x")

**Comment by samuelstroschein** [comment]
emerged in [INWEB-36](https://linear.app/opral/issue/INWEB-36/use-a-posthog-survey-to-offer-help-if-needed)

**Comment by samuelstroschein** [comment]
cc @felix.haeberle nobody clicks on your CTA in the product description. @jannes.blobel this seems better than [INWEB-36](https://linear.app/opral/issue/INWEB-36/use-a-posthog-survey-to-offer-help-if-needed)

**Comment by felixhaeberle** [comment]
Alright, so first things first. This has a bit of context:

1. The "Install VS Code" CTA originally didn't made perfect sense because when I'm browsing on the web, I do not have a high intent of installing a VS Code extension & therefore interrupting my flow – especially if this extension doesn't give a clear 1 step "Getting started" which will set everything up is distracting.
2. You expect such an extension to work ootb, meaning I don't scroll through "the technical details" – I just wanted to see some nice features and see how easy I can adopt them and how they work, so I will miss the Discord link – bringing me to my last point:
3. People would most likely browse a bit through the feature doc to get an understanding if they want to use this product and if its helpful, most likely they will **NOT** join a Discord for this, because raising questions about using a GUI tool feels kinda dump for developers (not so for Paraglide.js for example, where technical questions are quite normal).
   
   Furthermore: I feel like we are recreating this thing here when allowing for more than 1 button:

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/f34a1709-ff4c-481f-a951-60a1ba2e43ea/24036d11-4339-46ce-b7d7-424d868808db?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9mMzRhMTcwOS1mZjRjLTQ4MWYtYTk1MS02MGExYmEyZTQzZWEvMjQwMzZkMTEtNDMzOS00NmNlLWI3ZDctNDI0ZDg2ODgwOGRiIiwiaWF0IjoxNzEyMzA5NTI2LCJleHAiOjMzMjgyODY5NTI2fQ.VIuGgFo6FIPY4UZ4aKdEEtjcwV9oRPrC70LoGfjKzVI " alt="Bildschirmfoto 2024-04-05 um 11.17.58.png" width="895" height="644" />


This could gain some attention and will people click on Discord because they are lazy and don't want to scroll simply because its popping, but **the funnel into Discord also feels wrong.**

Leaving me with my proposal: 

* Don't clutter UI with popping buttons.
* Make it really easy to adopt the app & satisfy user! 
* Done.
