### ISSUE TITLE
Add license and pricing on doc layout

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang.com#62]
* We need this meta information

**Comment by NilsJacobsen** [comment]
We might mant to do something like that:

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/0cf35e99-023c-4f03-8b3f-5ae7d776a971/7388adee-9374-4598-98e8-2f1739bce5bf?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8wY2YzNWU5OS0wMjNjLTRmMDMtOGIzZi01YWU3ZDc3NmE5NzEvNzM4OGFkZWUtOTM3NC00NTk4LTk4ZTgtMmYxNzM5YmNlNWJmIiwiaWF0IjoxNzE1MDgyMjA1LCJleHAiOjMzMjg1NjQyMjA1fQ.ws1oEs074e1YMxJaRA3FpbivYK9xJ9G7HYQg6a8Mfb0 " alt="image.png" width="1280" height="814" />

* Remove the in-page nav and add meta information.

**Alternative:**

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/1c97111e-2155-49bc-bec9-c81c5f890681/c407a392-4ded-4eea-a22a-3cd845054d4f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8xYzk3MTExZS0yMTU1LTQ5YmMtYmVjOS1jODFjNWY4OTA2ODEvYzQwN2EzOTItNGRlZC00ZWVhLWEyMmEtM2NkODQ1MDU0ZDRmIiwiaWF0IjoxNzE1MDgyMjA1LCJleHAiOjMzMjg1NjQyMjA1fQ.hn5mQj7D4AfPdLfsGvSqRA0-fvEs0m2EgjT_SrQgngc " alt="image.png" width="1173" height="682" />

@niklas.buchfink @felix.haeberle @loris.sigrist do you need the in-page nav?

**Comment by LorisSigrist** [comment]
I like the in-page nav, not for navigation but to quickly scan what's on the page. I wouldn't remove. it. <br><br>Perhaps having the meta-info bottom-aligned in the left sidebar is the way to go? 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/7bc2a693-1a08-4a8f-9557-6d5ec3ee9975/171f295b-4df5-493d-a8d4-ff4741fb1d3c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC83YmMyYTY5My0xYTA4LTRhOGYtOTU1Ny02ZDVlYzNlZTk5NzUvMTcxZjI5NWItNGRmNS00OTNkLWE4ZDQtZmY0NzQxZmIxZDNjIiwiaWF0IjoxNzE1MDgzNzk5LCJleHAiOjMzMjg1NjQzNzk5fQ.0CZxhFPdplMNV1eHZWY-hlcB-RmDmMm0L0SrhjfoWns " alt="Screenshot 2024-05-07 at 14.09.48.png" width="641" height="372" />

**Comment by samuelstroschein** [comment]
hm the proposals don't give a marketplace feeling. this looks like a doc site (which is the purpose) even with meta information left and right.<br><br>having a header on top of the product page seems natural. there is no feeling of "this is contained in a marketplace site" coming up. all marketplaces i know have a top header 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/17694bf8-1bb4-48d5-a304-52cdb38ed48e/69dde4c0-1a48-4ea2-af0f-90328272c234?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8xNzY5NGJmOC0xYmI0LTQ4ZDUtYTMwNC01MmNkYjM4ZWQ0OGUvNjlkZGU0YzAtMWE0OC00ZWEyLWFmMGYtOTAzMjgyNzJjMjM0IiwiaWF0IjoxNzE1MDg4NDIwLCJleHAiOjMzMjg1NjQ4NDIwfQ.HIKjq0IT9dQog_vYnwti6dUz7S-kHjIs8AfBO9KwT00 " alt="CleanShot 2024-05-07 at 09.20.58@2x.png" width="2732" height="2136" />

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/e8cb46f6-d874-499f-a13c-370ebc20fece/aab4ea2d-af3f-4d75-99ff-05d925f35669?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9lOGNiNDZmNi1kODc0LTQ5OWYtYTEzYy0zNzBlYmMyMGZlY2UvYWFiNGVhMmQtYWYzZi00ZDc1LTk5ZmYtMDVkOTI1ZjM1NjY5IiwiaWF0IjoxNzE1MDg4NDIwLCJleHAiOjMzMjg1NjQ4NDIwfQ.EoPlwQdHml-AUOamPSKh1-k5XTe0xKKI9eKqWJ9rP-o " alt="CleanShot 2024-05-07 at 09.20.09@2x.png" width="2848" height="1682" />

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/bdc624e5-1771-4c46-91f6-ba5b5488743d/6a9782d4-c26c-4d88-bd66-d828e03cbc9c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9iZGM2MjRlNS0xNzcxLTRjNDYtOTFmNi1iYTViNTQ4ODc0M2QvNmE5NzgyZDQtYzI2Yy00ZDg4LWJkNjYtZDgyOGUwM2NiYzljIiwiaWF0IjoxNzE1MDg4NDIwLCJleHAiOjMzMjg1NjQ4NDIwfQ.2SDfzpZqA-tnGSGSaGVwFFqjMmhrf9utNIVmNZqLy44 " alt="CleanShot 2024-05-07 at 09.23.22@2x.png" width="2844" height="2338" />

## Proposal 

1. Have a top header to give a marketplace feeling
2. Put the meta on the right because navigation is more important (on the left)

**Comment by NilsJacobsen** [comment]
I pushback to get a huge header. We might use a super small one, but I want a flexible system that can feel like a docs page, a landing page and even a marketplace page. Having a huge one would definitely hurt the landing page maybe also the docs. Especially, if it would contain a H1 kind of thing.<br><br>At first what are the app devs thinking? How is your product presented in the best possible way?

**Comment by samuelstroschein** [comment]
Roger. FYI I am not advocating for a large banner. Just that the product page does not give a "product"/marketplace feeling with the current re-design. seem to require a feeling of "they are embedded on inlang.com" and users con browse around.

**Comment by NilsJacobsen** [comment]
Alright, thanks for the feedback. I would say a small header is still in, and I rely on the feedback of the app devs here:)

**Comment by felixhaeberle** [comment]
@samuel.stroschein @nils.jacobsen <br>Whats with adding a small box over the in-page nav with meta ?

**Comment by NilsJacobsen** [comment]
Okey now I have two options.

1. Add the meta info on the right above the in-page nav
2. Add a super condensed header (example underneath)

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/ea27576b-d457-443b-bd29-27536f7a6ad0/2bcdd1d0-a189-46b0-a8ce-27b5b98f9614?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9lYTI3NTc2Yi1kNDU3LTQ0M2ItYmQyOS0yNzUzNmY3YTZhZDAvMmJjZGQxZDAtYTE4OS00NmIwLWE4Y2UtMjdiNWI5OGY5NjE0IiwiaWF0IjoxNzE1MTc5OTk1LCJleHAiOjMzMjg1NzM5OTk1fQ.E2Lvge_uoRqwYicuqG-VJ-NaffVQdJ5Jb-QQgd1SOuY " alt="image.png" width="964" height="608" />

I tend to do the header. What do you think?

**Comment by samuelstroschein** [comment]
uhhh the header is good

**Comment by felixhaeberle** [comment]
hot 🔥
